name: CI API Tests
on:
  push:
    branches:
      - "*"
  pull_request:
    types: ['opened']
jobs:
  tests: 
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
    - name: Install dependecies
      working-directory: ./lesson13-14
      run: npm ci
    - name: Run api test
      working-directory: ./lesson13-14
      run: npm run test:node-setup