name: CI API Tests
on:
  schedule:
    - cron:  '5 * * * *'
  push:
    branches:
      - "*"
  pull_request:
    types: ['opened']
jobs:
  lint-api: 
    name: 'Lint API tests folder'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
    - name: Install dependecies
      working-directory: ./lesson-13-14
      run: | 
        echo "LINT API TESTS"
        npm ci
    - name: Run lint
      working-directory: ./lesson-13-14
      run: npm run lint
  tests: 
    name: 'API tests Jest'
    if: ${{ always() }}
    needs: lint-api
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
    - name: Install dependecies
      working-directory: ./lesson-13-14
      run: npm ci
    - name: Run api test
      working-directory: ./lesson-13-14
      run: npm run test:node-setup